build_resources_dir: 'C:\BuildResources'

hyperg_version: 0.2.4
hyperg_package_url: "https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v{{ hyperg_version }}/hyperg_{{ hyperg_version }}_windows-x64.zip"
hyperg_package_path: "{{ build_resources_dir }}\hyperg_0.2.3_windows-x64.zip"

buildbot_build_resources_url: "https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl"
buildbot_build_resources_path: "{{ build_resources_dir }}\pywin32-221-cp36-cp36m-win_amd64.whl"

geth_package_url: "https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.zip"
geth_install_dir: "{{ build_resources_dir }}\geth-windows-amd64-1.7.2-1db4ecdc"
geth_package_path: "{{ build_resources_dir }}\geth-windows-amd64-1.7.2-1db4ecdc.zip"

golem_electron_url: "https://github.com/golemfactory/golem-electron/releases/download/0.1.4/win-unpacked.zip"
golem_electron_package_path: "{{ build_resources_dir }}\win-unpacked.zip"
golem_electron_path: "{{ build_resources_dir }}\win-unpacked"

docker_package_url: "https://download.docker.com/win/stable/DockerToolbox.exe"
docker_package_path: "{{ build_resources_dir }}\DockerToolbox.exe"

vc_redist_url: "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe"
vc_redist_path: "{{ build_resources_dir }}\vc_redist.x64.exe"
