- name: reconfigure buildbot
  become_user: buildbot
  command: /var/lib/virtualenv/buildbot-master/bin/buildbot restart --clean /home/buildbot/master


- name: restart buildbot master service
  systemd:
    name: buildbot-master.service
    daemon_reload: yes
    state: restarted
