language: generic

os: osx
osx_image: xcode8.2  # OS X 10.12

branches:
  only:
    - master
    - develop

cache:
  directories:
    - /usr/local/Cellar
    - $HOME/venv
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip

before_install:
  - brew update
  - brew install qt@5.7 ethereum/ethereum/ethereum openexr freeimage

  - git clone https://github.com/mfranciszkiewicz/golem-hyperdrive --depth 1
  - cd golem-hyperdrive && npm install --save && cd ..
  - node golem-hyperdrive/src/main.js &

  - sudo -HE pip install --upgrade pip setuptools virtualenv
  - pip install https://github.com/golemfactory/golem/wiki/wheels/sip-4.19-cp27-cp27m-macosx_10_12_x86_64.whl
  - pip install https://github.com/golemfactory/golem/wiki/wheels/PyQt5-5.7.1-cp27-cp27m-macosx_10_12_x86_64.whl
  - sudo -HE pip install -r requirements.txt
  - sudo -HE install -r requirements-test.txt
  - sudo -HE python setup.py develop

script: python -m pytest tests
