language: generic


os: osx
osx_image: xcode8.3  # OS X 10.12

branches:
  only:
    - master
    - develop

env:
    - GETH_VER=geth-darwin-amd64-1.6.4-9c2882b2

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip

before_install:
  - brew install qt@5.7 openexr freeimage

  - wget https://gethstore.blob.core.windows.net/builds/${GETH_VER}.tar.gz
  - tar xvf ${GETH_VER}.tar.gz
  - sudo -HE mv ${GETH_VER}/geth /usr/local/bin

  - git clone https://github.com/mfranciszkiewicz/golem-hyperdrive --depth 1
  - cd golem-hyperdrive && npm install --save && cd ..
  - node golem-hyperdrive/src/index.js &

  - sudo -HE pip install --upgrade pip setuptools six
  - pip install https://github.com/golemfactory/golem/wiki/wheels/sip-4.19-cp27-cp27m-macosx_10_12_x86_64.whl
  - pip install https://github.com/golemfactory/golem/wiki/wheels/PyQt5-5.7.1-cp27-cp27m-macosx_10_12_x86_64.whl
  - sudo -HE pip install -r requirements.txt
  - sudo -HE pip install -r requirements-test.txt
  - sudo -HE python setup.py develop

script: python -m pytest tests
